### ISSUE TITLE
Tesorflow Version

### ISSUE THREAD

**Issue by Gyyz** [LeonCrashCode/AttentionTargetSentiment#2]
https://github.com/CooDL/Targeted-Sentiment-analysis-with-memory-network-attention

**Comment by Gyyz** [comment]
ok

**Comment by l11x0m7** [comment]
Hi, is it really the tensorflow version of this paper 'Attention Target Sentiment Model'?

**Comment by Gyyz** [comment]
included in '/lib/model/sentiment' dir, and use the tf 0.12headrc version

**Comment by l11x0m7** [comment]
Thanks for your quick reply!
