### ISSUE TITLE
About using GPU

### ISSUE THREAD

**Issue by lixin4ever** [LeonCrashCode/AttentionTargetSentiment#5]
Hi,
Thanks for releasing your code.
I tried to build the code with the additional cmake option -DBACKEND=cuda to enable the gpu support and it is ok during the compiling process. However, when I trained the model on GPU, I always encountered the error "Segmentation fault (core dumped)" right after the "initializing CUDA". Do you know how to solve the problem?

**Comment by lixin4ever** [comment]
Hi Jiangming,
    Sorry for bothering you again. In you code, is the batch size equal to 1? (I didn't find the batching operation...)

**Comment by LeonCrashCode** [comment]
Yes, It doesn’t use batch

**Comment by bwang482** [comment]
@LeonCrashCode Can I run your code with GPU? 

@lixin4ever Are you running it with GPU? 

Thanks!

**Comment by lixin4ever** [comment]
@bluemonk482  I just run the code using CPU.
