### ISSUE TITLE
Some implement issues

### ISSUE THREAD

**Issue by pochih** [LeonCrashCode/AttentionTargetSentiment#7]
Hello, I have some questions

1. Why do you not choose 300 dimension GloVe or google pretrained word2vec, but choose 200 dimension GloVe?

2. How to deal with the case when left / right context is empty?
There will be no input for the attention network.

Thanks!

**Comment by LeeSureman** [comment]
To the 2nd question, he add the start and end tag to the sentence. When the left context is empty, the model only attends to the part of tag.

**Comment by pochih** [comment]
I already ask the authors of the paper :)
Still thanks!

**Comment by LeonCrashCode** [comment]
Thanks for your questions.
@pochih , We do not investigate which pretrained word embeddings are best, so I just take 200 dimension GloVe in our experiments, but you could try other word embeddings, like Elmo or others. 

@LeeSureman is right for the second questions
